# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [3]:
import numpy as np

In [4]:
#Crear un arreglo de ceros de longitud 12
print(np.zeros(12))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
#Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
arreglo_Ceros = np.zeros(10)
arreglo_Ceros[5] = 10
print(arreglo_Ceros)

[ 0.  0.  0.  0.  0. 10.  0.  0.  0.  0.]


In [14]:
#Crear un arreglo que tenga los números del 10 al 49
arreglo = np.arange(10,50)
arreglo

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [20]:
#Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
lista = [[0, 1, 2, 4], [5, 6, 7, 8]]
Arreglo2d = np.array(lista)
Arreglo2d

array([[0, 1, 2, 4],
       [5, 6, 7, 8]])

In [40]:
#Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
Nuevo_array = (np.random.randn(100))
Nuevo_array

array([-1.51704095,  0.79138845,  0.51443143,  1.13396267, -0.66778672,
       -0.03673141, -1.01828086,  1.4408904 , -0.1974549 , -0.62325479,
       -0.72321793, -0.39513448,  0.03592827, -0.51562645, -1.08678852,
       -0.04283032,  0.56108318, -1.26152934,  0.73247549, -1.2589378 ,
       -0.82939324, -1.10997047, -1.51079933, -0.47583403, -0.22059166,
        0.21721647,  0.17545815,  0.36794912,  0.38808987, -0.11045907,
       -0.42295578,  0.4082436 , -0.33511879,  0.54900399,  0.43998567,
        0.30153446, -0.82926226,  0.79000541, -0.51496772, -0.38165803,
       -1.05279223, -1.56575447, -0.90201997,  1.70270789,  1.65230614,
       -1.44040298, -0.90280002,  2.57935195, -1.09438815, -0.29430609,
        0.5668412 , -0.46195352,  2.41495115,  1.11366571,  0.18719709,
        0.30576247, -0.81913597, -0.30601871,  0.04478224,  0.744603  ,
        0.09842954, -2.03811205, -1.46975522,  0.66629632,  0.63688558,
        2.15356469,  0.74659085,  1.60375933,  0.46598628, -0.80

In [41]:
#MEDIA
np.mean(Nuevo_array)

-0.0493638486223874

In [42]:
#VARIANZA
np.var(Nuevo_array)

1.191165559971545

In [43]:
#Calcular la media de un arreglo usando np.sum
np.sum(Nuevo_array)/100


-0.0493638486223874

In [10]:
#Calcular la varianza de un arreglo usando np.sum y np.mean
arreglo = np.array([1, 2, 3, 4, 5])

media = np.mean(arreglo)
varianza = np.sum((arreglo - media)**2) / len(arreglo)

print(varianza)


2.0


In [49]:
#Crear un array de números aleatorios usando np.random.randn
Array= (np.random.randn(10))
Array

array([ 1.14187684,  0.00444007, -0.81174339,  1.43639151,  0.316907  ,
        0.59664761, -0.08900267,  0.80889003, -1.35202867, -0.47229065])